# Generated by Django 3.2.5 on 2021-07-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0003_rename_business_id_businessfeeditem_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled form', max_length=255)),
                ('description', models.CharField(default='description', max_length=550)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled part', max_length=255)),
                ('description', models.CharField(default='Part Specification', max_length=500)),
                ('is_char', models.BooleanField(default=False)),
                ('is_int', models.BooleanField(default=False)),
                ('is_datetime', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('is_decimal', models.BooleanField(default=False)),
                ('is_date', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_api.form')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='new option', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('text_field', models.CharField(default='text', max_length=255)),
                ('number_field', models.IntegerField(default=0)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime_field', models.DateTimeField(auto_now_add=True)),
                ('file_field', models.FileField(upload_to='')),
                ('date_field', models.DateField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_api.part')),
            ],
        ),
    ]
