# Generated by Django 3.2.5 on 2021-07-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0004_form_option_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessFeedItem',
        ),
    ]
