# Generated by Django 3.2.5 on 2021-07-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0005_delete_businessfeeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='file_field',
        ),
    ]
